### ISSUE TITLE
peer to peer code review day 2

### ISSUE THREAD

**Issue by Abass-rashid** [sireclifford/Microverse-Student-Project-1#4]
HI @sireclifford 
1. kindly  remove the outline from the form inputs
2.   I think you're supposed to change social  icons from png to SVG for easy customization
3.  Kindly stick to the  Figma template  as much as possible
4.  Kindly remove  breaking point from your HTML and set max-width in the style instead
5. Please avoid using more than one h1 for easy accessibility

**Comment by sireclifford** [comment]
Thank you @Abass-rashid .
The stated issues have been resolved.
